#!/bin/bash
TARGET="/home/{{ ansible_ssh_user }}/public_html/"
GIT_DIR="/home/{{ ansible_ssh_user }}/devbertholdo/{{ ansible_ssh_user }}.git/"
BRANCH="master"

while read oldrev newrev ref
do
        # apenas verificando se o branch e o master.
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref recebido. Realizando deploy no branch ${BRANCH} para /home/{{ ansible_ssh_user }}/public_html/"
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
                echo "Deploy realizado com sucesso!"
        else
                echo "Ref $ref recebido. Deploy negado: somente o ramo ${BRANCH} pode ser implantado neste servidor."
        fi
done
